NumPy:
------------
- NumPy stands for Numerical Python which is a library consists of multidimensional array objectsand a collection of manipulating functions for preprocessing those arrays and this is the core library for scientific computing in python
- Installing numpy library
- importing numpy library
- creation and accessing of arrays in different dimensions

In [1]:
# Installing numpy library
! pip install numpy

In [2]:
# importing the numpy library
import numpy as np

In [3]:
k1 = [1,2,3,4,5]
k2 = [45,"abc","xyz",98.34,29,17]
k3 = ["a","b","c"]

#### Creating the array

In [5]:
## 1-d array
a = np.array(k1)
print(a)

[1 2 3 4 5]


In [6]:
a.dtype  # checking the array datatype

dtype('int32')

In [7]:
b = np.array(k2)
b.dtype

dtype('<U11')

In [8]:
c = np.array(k3)
c.dtype

dtype('<U1')

In [9]:
len(c)

3

In [10]:
c

array(['a', 'b', 'c'], dtype='<U1')

In [11]:
a.ndim    # returns the dimension of an array

1

In [12]:
a.size    # returns the count of elements present in an array

5

In [13]:
a.itemsize  # each element size

4

In [14]:
a.nbytes   # checking the memory space oocupied by array

20

In [15]:
a.shape

(5,)

In [16]:
k = np.linspace(1,10,20)  # creating array within the given range with required no of elements
k 

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [17]:
k7 = np.linspace(1,20,50)
k7

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

In [19]:
kl = np.logspace(1,10,20) # creating the array within given range with required no of 
                        # elements with their log values
kl

array([1.00000000e+01, 2.97635144e+01, 8.85866790e+01, 2.63665090e+02,
       7.84759970e+02, 2.33572147e+03, 6.95192796e+03, 2.06913808e+04,
       6.15848211e+04, 1.83298071e+05, 5.45559478e+05, 1.62377674e+06,
       4.83293024e+06, 1.43844989e+07, 4.28133240e+07, 1.27427499e+08,
       3.79269019e+08, 1.12883789e+09, 3.35981829e+09, 1.00000000e+10])

In [21]:
ar = np.arange(1,11,2)  # creating an array of elements within the given range with step value
ar

array([1, 3, 5, 7, 9])

In [22]:
f = np.full(10,"python") # repeating an element required no of times and making them to an array
f

array(['python', 'python', 'python', 'python', 'python', 'python',
       'python', 'python', 'python', 'python'], dtype='<U6')

In [24]:
f1 = np.full(5,"1 9 6")
f1

array(['1 9 6', '1 9 6', '1 9 6', '1 9 6', '1 9 6'], dtype='<U5')

In [26]:
f2 = np.full(12,3)
f2

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [29]:
z = np.zeros(10)  # repeating 0's for given no of times and returns with float data type
print(z.dtype)
z

float64


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
z1 = np.zeros(6,dtype=int) # repeating 0's with required no of times and returns in int datatype
z1

array([0, 0, 0, 0, 0, 0])

In [32]:
z2 = np.ones(4) # repeating 1 for defined no of times
z2

array([1., 1., 1., 1.])

In [36]:
e = np.eye(3,3) # returns the identity array with mentioned rows and columns
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
## 2-d array: combination of more number of 1-d arrays
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
a2.dtype
a2.nbytes
a2.size
a2.itemsize
a2.ndim
a2.shape

(3, 3)

In [46]:
len(a2) # number of rows

3

In [47]:
## 3-d array : combination of more number of 2-d arrays
a3 = np.array([
    [[1,2],[3,4],[5,6]],
    [[7,8],[9,10],[11,12]]
])
a3

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [48]:
a3.ndim

3

In [49]:
len(a3)

2

In [51]:
# multi dimensional arrays
an = np.array([1,2,3,4,5,67,89],ndmin = 20)
an

array([[[[[[[[[[[[[[[[[[[[ 1,  2,  3,  4,  5, 67, 89]]]]]]]]]]]]]]]]]]]])

In [52]:
an.ndim

20