In [1]:
import numpy as np

#### Accessing the elements from tha array

In [2]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a3 = np.array([[[1,2],[6,7]],[[8,9],[3,4]]])

In [4]:
a1

array([1, 2, 3, 4, 5])

In [5]:
a1[2]

3

In [7]:
a1[-3]

3

In [8]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
a2[1][0]

4

In [12]:
a2[1,0]

4

In [13]:
a2[:,-1:] 

array([[3],
       [6],
       [9]])

In [16]:
a2[:,-1:]

array([[3],
       [6],
       [9]])

In [17]:
a2[:,1:2]

array([[2],
       [5],
       [8]])

In [18]:
a2[:,0::2]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [23]:
a3

array([[[1, 2],
        [6, 7]],

       [[8, 9],
        [3, 4]]])

In [22]:
a3[[1,0],[0,1]]  # (1,0)(0,1) # fancy indexing

array([[8, 9],
       [6, 7]])

In [24]:
a3[[1,1,0],[0,1,0]] # (1,0)(1,1)(0,0)

array([[8, 9],
       [3, 4],
       [1, 2]])

In [28]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
b[[1,0,1,0],[0,1,2,1]] # (1,0)(0,1)(1,2)(0,1)

array([4, 2, 6, 2])

In [29]:
# 2,6,7
b[[0,1,2],[1,2,0]]

array([2, 6, 7])

In [31]:
b[:,-1]

array([3, 6, 9])

#### shape of arrays

In [33]:
a1.shape,a2.shape,a3.shape

((5,), (3, 3), (2, 2, 2))

In [35]:
a = np.arange(1,21)
a.size

20

In [38]:
# 20,1
# 4,5
# 5,4
# 2,10
b1 = a.reshape(4,5)
b1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [39]:
# (2,5,2)(2,2,5)(5,2,2)
b3 = a.reshape(2,5,2)
b3

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [40]:
b3.reshape(4,-1)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [41]:
b3.reshape(-1,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [42]:
b3.reshape(-1,2,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [43]:
a = np.arange(1,11).reshape(2,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [44]:
a1 = np.arange(1,10).reshape(-1,3,3)
a1

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

### Iteration of arrays

In [46]:
for i in a:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [47]:
a = np.array([1,2,3,4])
a2 = np.array([[1,2],[3,4],[5,6]])
a3 = np.array([[[34,67]],[[67,89]]])

In [48]:
## 1-d array looping
for i in a:
    print(i)

1
2
3
4


In [49]:
## 2-d array looping
for i in a2:  # i holds rows
    for j in i: # j holds row elements
        print(j,end = " ")

1 2 3 4 5 6 

In [50]:
## 3-d array looping
for i in a3:        # i holds 2-d array
    for j in i:     # j holds rows
        for k in j: # k holds element
            print(k)
            

34
67
67
89


In [51]:
for i in np.nditer(a3):
    print(i)

34
67
67
89


In [53]:
# Random Methods
np.random.randint(150) # integer value within in a given range

64

In [54]:
np.random.randint(500,1000)

929

In [57]:
np.random.rand() # float value within the range 0 to 1

0.3184955225325765

In [58]:
np.random.randint(1,100,size=(20)) # 1-d array with defined no of times in the given range

array([72, 40, 60, 90,  4, 93, 53, 86,  8, 24, 46, 18, 84, 77, 53, 26, 56,
       72,  4, 91])

In [59]:
np.random.randint(20,50,10)

array([24, 46, 42, 38, 28, 40, 24, 21, 27, 26])

In [60]:
np.random.randint(60,size = (3,4)) ## 2-d array

array([[57, 55,  0, 33],
       [53, 20, 40, 28],
       [14,  8, 10, 27]])

In [61]:
np.random.randint(150,200,size = (2,3,4,4)) # 4-d array

array([[[[191, 187, 154, 198],
         [199, 191, 161, 185],
         [170, 158, 181, 172],
         [175, 168, 194, 190]],

        [[177, 163, 198, 198],
         [174, 198, 160, 165],
         [190, 164, 151, 177],
         [183, 192, 186, 199]],

        [[150, 177, 195, 151],
         [174, 167, 183, 193],
         [157, 156, 188, 153],
         [166, 172, 163, 188]]],


       [[[172, 192, 160, 190],
         [152, 170, 182, 168],
         [185, 189, 160, 171],
         [163, 198, 171, 170]],

        [[179, 151, 169, 165],
         [175, 180, 157, 193],
         [191, 187, 178, 190],
         [187, 172, 189, 161]],

        [[155, 172, 157, 188],
         [152, 181, 154, 156],
         [166, 164, 164, 164],
         [165, 172, 165, 186]]]])

In [63]:
np.random.choice([12,34,56,8,9,268,98])

12

In [2]:
g = np.random.choice([14,34,67,89,54,23,26,5,10],size = (3,3))
g

array([[14, 10, 14],
       [10, 67, 23],
       [14, 26, 54]])

In [14]:
h = np.random.choice([14,34,67,89,54,23,26,5,10],size = (2,3,3))
h

array([[[89, 54,  5],
        [ 5,  5, 26],
        [10, 89, 34]],

       [[14, 89, 23],
        [14, 10, 89],
        [67, 23, 54]]])

In [12]:
np.random.shuffle(h) # places of the elements in the array will be changed

In [13]:
h

array([[[ 5, 14, 10],
        [ 5, 54, 67],
        [54, 10, 26]],

       [[10, 34, 14],
        [54, 89, 14],
        [14, 67, 26]]])

In [15]:
np.random.randn(10) # returns the +ve and -ve values in defined range

array([ 0.03037412,  1.05767965, -0.04525044, -0.8575139 ,  1.46707181,
        0.40184956, -0.12069603, -1.29094111,  1.7475852 , -1.27499108])

In [16]:
# normal distribution
np.random.normal()

0.6132077998263012

In [20]:
# binomial distribution
np.random.binomial(10,p=[0.1],size = (2,2))

array([[1, 1],
       [1, 2]])