In [1]:
import numpy as np

#### Joining of arrays

In [2]:
### 1-d array
a = np.arange(1,10)
b = np.arange(11,20)

In [3]:
c = np.concatenate((a,b))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [5]:
### 2-d array
c = a.reshape(3,3)
d = b.reshape(3,3)
e = np.concatenate((c,d))
e

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

### statistical and Math operations on arrays

In [9]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.min(c)  ## minimum value

1

In [11]:
np.max(c)   ## maximum value 

9

In [12]:
c.min()

1

In [13]:
c.max()

9

In [14]:
c.argmin()  # min value index

0

In [15]:
c.argmax() # max value index

8

In [18]:
np.argmin(c,0) # 1--> row wise and 0--> column wise

array([0, 0, 0], dtype=int64)

In [19]:
np.argmax(c,0)

array([2, 2, 2], dtype=int64)

In [20]:
c.sum()

45

In [21]:
np.sum(c)  # sum of all the array elements

45

In [22]:
np.sum(c,1)  ## sum of the row elements

array([ 6, 15, 24])

In [23]:
np.sum(c,0)   ## sum of the column elements

array([12, 15, 18])

In [24]:
c.mean() # mean of the array elements

5.0

In [26]:
np.median(c)   # median of the array elements

5.0

In [27]:
np.var(c)   # variance of the array elements

6.666666666666667

In [28]:
np.std(c)  # standard deviation of the array elements

2.581988897471611

In [31]:
np.average(c)   # average of the array elements

5.0

In [33]:
np.corrcoef(c)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
d = np.array([[67,8,23],[44,26,987],[1,89,13]])
d

array([[ 67,   8,  23],
       [ 44,  26, 987],
       [  1,  89,  13]])

In [35]:
d.sort()

In [36]:
d

array([[  8,  23,  67],
       [ 26,  44, 987],
       [  1,  13,  89]])

In [37]:
d.sort(axis = 0)

In [38]:
d

array([[  1,  13,  67],
       [  8,  23,  89],
       [ 26,  44, 987]])

### Arithmetic operations

In [39]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.add(a,b)

array([12, 14, 16, 18, 20, 22, 24, 26, 28])

In [43]:
np.subtract(a,b)

array([-10, -10, -10, -10, -10, -10, -10, -10, -10])

In [44]:
np.multiply(a,b)

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171])

In [45]:
np.divide(a,b)

array([0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333,
       0.375     , 0.41176471, 0.44444444, 0.47368421])

In [47]:
a * b

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171])

In [48]:
np.exp(a)  # exponentiation

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [49]:
np.log(a)  # logaritmic values of the array elements

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [50]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [51]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [52]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [53]:
a.dot(b)

735

In [54]:
c.dot(a)

ValueError: shapes (3,3) and (9,) not aligned: 3 (dim 1) != 9 (dim 0)

In [55]:
np.array_equal(a,b) # array wise comparision

False

In [56]:
k = np.copy(a)
k

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
np.array_equal(a,k)

True

In [58]:
np.tan(c)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

In [59]:
np.log2(c) # log values with base2

array([[0.        , 1.        , 1.5849625 ],
       [2.        , 2.32192809, 2.5849625 ],
       [2.80735492, 3.        , 3.169925  ]])

In [60]:
np.log10(a)  # log values with base 10

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251])

In [62]:
np.remainder(c,3)  ## remainder of the each array element

array([[1, 2, 0],
       [1, 2, 0],
       [1, 2, 0]], dtype=int32)

In [65]:
np.sum(c,1)

array([ 6, 15, 24])

In [66]:
np.degrees(c)  ## degrees of the array elements

array([[ 57.29577951, 114.59155903, 171.88733854],
       [229.18311805, 286.47889757, 343.77467708],
       [401.07045659, 458.3662361 , 515.66201562]])

In [67]:
np.mod(a,4)

array([1, 2, 3, 0, 1, 2, 3, 0, 1], dtype=int32)

In [68]:
np.power(b,2)

array([121, 144, 169, 196, 225, 256, 289, 324, 361], dtype=int32)

In [70]:
np.reciprocal(c,dtype = float)

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667],
       [0.14285714, 0.125     , 0.11111111]])

In [71]:
np.diff(c)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [72]:
np.ediff1d(c) ## converts the array into 1-d array and calculates the 
              ## consecutive difference of each element

array([1, 1, 1, 1, 1, 1, 1, 1])

In [73]:
np.i0(c)  ## bessel function

array([[   1,    2,    4],
       [  11,   27,   67],
       [ 168,  427, 1093]])

In [74]:
a = np.array([1+2j,3+4j,9+8j])
a

array([1.+2.j, 3.+4.j, 9.+8.j])

In [75]:
np.real(a)  ## real values of the given array elements

array([1., 3., 9.])

In [76]:
np.imag(a)  ## imaginary values of the given array elements

array([2., 4., 8.])

In [77]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
c.T  # transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [80]:
np.transpose(c) # transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Ravel and flatten:
---------------------------
- Ravel
    - ravel is a function used to create a copy of the original array. 
    - when any changes made in the duplicate array those will be applied in the original array.
- Flatten
    - Flatten is a function used to create copy of the original array.
    - When any changes made in the duplicate array those wont be applied in the original array.

In [81]:
org = np.arange(1,10)
org

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
cop = org.ravel()
cop

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
cop[2]= 78

In [84]:
cop

array([ 1,  2, 78,  4,  5,  6,  7,  8,  9])

In [85]:
org

array([ 1,  2, 78,  4,  5,  6,  7,  8,  9])

In [86]:
flat = org.flatten()
flat

array([ 1,  2, 78,  4,  5,  6,  7,  8,  9])

In [87]:
flat[7] = 999

In [88]:
flat

array([  1,   2,  78,   4,   5,   6,   7, 999,   9])

In [89]:
org

array([ 1,  2, 78,  4,  5,  6,  7,  8,  9])

In [91]:
np.hstack(d)

array([  1,  13,  67,   8,  23,  89,  26,  44, 987])

In [92]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
np.vstack((c,d))

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [  1,  13,  67],
       [  8,  23,  89],
       [ 26,  44, 987]])

In [95]:
h = np.hstack((c,d))
h

array([[  1,   2,   3,   1,  13,  67],
       [  4,   5,   6,   8,  23,  89],
       [  7,   8,   9,  26,  44, 987]])

In [96]:
np.save("myarray",h)

In [97]:
np.load("myarray.npy")

array([[  1,   2,   3,   1,  13,  67],
       [  4,   5,   6,   8,  23,  89],
       [  7,   8,   9,  26,  44, 987]])

In [98]:
np.savez("myarray2.npz",a,b)

In [100]:
np.load("myarray2.npz")

In [101]:
np.r_[c,d] # row wise stacking or vertical stacking

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [  1,  13,  67],
       [  8,  23,  89],
       [ 26,  44, 987]])

In [102]:
np.c_[c,d] # column wise stacking or horizontal stacking

array([[  1,   2,   3,   1,  13,  67],
       [  4,   5,   6,   8,  23,  89],
       [  7,   8,   9,  26,  44, 987]])

In [103]:
np.column_stack((c,d))  ## c_ and hstack

array([[  1,   2,   3,   1,  13,  67],
       [  4,   5,   6,   8,  23,  89],
       [  7,   8,   9,  26,  44, 987]])

In [104]:
np.row_stack((c,d))   # r_ and vstack

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [  1,  13,  67],
       [  8,  23,  89],
       [ 26,  44, 987]])

In [112]:
## splitting arrays
np.hsplit(a,3)

[array([1.+2.j]), array([3.+4.j]), array([9.+8.j])]

In [106]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [116]:
np.vsplit(c,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [113]:
a.size

3

In [119]:
np.hsplit(c,3)

[array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]]), array([[3],
        [6],
        [9]])]